/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    calendar: typeof import('./src/pages/teams/[id]/matches.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DHome: typeof import('./src/components/DHome.vue')['default']
    LeaguesTabs: typeof import('./src/components/LeaguesTabs.vue')['default']
    MatchesTabs: typeof import('./src/components/MatchesTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Team: typeof import('./src/components/Team.vue')['default']
    Teamcalendar: typeof import('./src/components/teamcalendar.vue')['default']
  }
}
