/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/leagues': RouteRecordInfo<'/leagues', '/leagues', Record<never, never>, Record<never, never>>,
    '/matches': RouteRecordInfo<'/matches', '/matches', Record<never, never>, Record<never, never>>,
    '/teams/[id]/matches': RouteRecordInfo<'/teams/[id]/matches', '/teams/:id/matches', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/teams/all': RouteRecordInfo<'/teams/all', '/teams/all', Record<never, never>, Record<never, never>>,
  }
}
